export const sidebar: string;
export const search: string;
export const main: string;
export const copyright: string;
export const line: string;
export const inputIcon: string;
export const stuff: string;
export const inputWrapper: string;
export const settings: string;
